export default {
  DBY: 'bible-dby',
  OST: 'bible-ost',
  BDS: 'bible-bds',
  CHU: 'bible-chu',
  FMAR: 'bible-fmar',
  FRC97: 'bible-frc97',
  NBS: 'bible-nbs',
  NEG79: 'bible-neg79',
  NVS78P: 'bible-nvs78p',
  S21: 'bible-s21',
  KJF: 'bible-kjf',
  KJV: 'bible-kjv',
  NKJV: 'bible-nkjv',
  ESV: 'bible-esv',
  LSG: 'bible-lsg-1910',
  NIV: 'bible-niv',
  POV: 'bible-pov',
  BHS: 'bible-hebrew',
  SBLGNT: 'bible-greek',
  NFC: 'bible-nfc',
  PDV2017: 'bible-pdv2017',
  BFC: 'bible-bfc',
  BCC1923: 'bible-bcc1923',
  LXX: 'bible-lxx',
  TR1624: 'bible-TR1624',
  TR1894: 'bible-TR1894',
}
