/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as EulaRouteImport } from './routes/eula'
import { Route as EulaEnRouteImport } from './routes/eula-en'
import { Route as GiveRouteImport } from './routes/give'
import { Route as HowToDeleteDataRouteImport } from './routes/how-to-delete-data'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FrIndexRouteImport } from './routes/fr.index'
import { Route as FrDataDeletionRouteImport } from './routes/fr.data-deletion'
import { Route as FrEulaRouteImport } from './routes/fr.eula'
import { Route as FrEulaEnRouteImport } from './routes/fr.eula-en'
import { Route as FrGiveRouteImport } from './routes/fr.give'
import { Route as FrHowToDeleteDataRouteImport } from './routes/fr.how-to-delete-data'
import { Route as FrPolitiqueDeConfidentialiteRouteImport } from './routes/fr.politique-de-confidentialite'
import { Route as FrPrivacyPolicyRouteImport } from './routes/fr.privacy-policy'
import { Route as StudiesIdRouteImport } from './routes/studies.$id'
import { Route as FrStudiesIdRouteImport } from './routes/fr.studies.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const EulaRoute = EulaRouteImport.update({
  id: '/eula',
  path: '/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const EulaEnRoute = EulaEnRouteImport.update({
  id: '/eula-en',
  path: '/eula-en',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToDeleteDataRoute = HowToDeleteDataRouteImport.update({
  id: '/how-to-delete-data',
  path: '/how-to-delete-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrDataDeletionRoute = FrDataDeletionRouteImport.update({
  id: '/fr/data-deletion',
  path: '/fr/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const FrEulaRoute = FrEulaRouteImport.update({
  id: '/fr/eula',
  path: '/fr/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const FrEulaEnRoute = FrEulaEnRouteImport.update({
  id: '/fr/eula-en',
  path: '/fr/eula-en',
  getParentRoute: () => rootRouteImport,
} as any)
const FrGiveRoute = FrGiveRouteImport.update({
  id: '/fr/give',
  path: '/fr/give',
  getParentRoute: () => rootRouteImport,
} as any)
const FrHowToDeleteDataRoute = FrHowToDeleteDataRouteImport.update({
  id: '/fr/how-to-delete-data',
  path: '/fr/how-to-delete-data',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPolitiqueDeConfidentialiteRoute =
  FrPolitiqueDeConfidentialiteRouteImport.update({
    id: '/fr/politique-de-confidentialite',
    path: '/fr/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const FrPrivacyPolicyRoute = FrPrivacyPolicyRouteImport.update({
  id: '/fr/privacy-policy',
  path: '/fr/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesIdRoute = StudiesIdRouteImport.update({
  id: '/studies/$id',
  path: '/studies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FrStudiesIdRoute = FrStudiesIdRouteImport.update({
  id: '/fr/studies/$id',
  path: '/fr/studies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/eula': typeof EulaRoute
  '/eula-en': typeof EulaEnRoute
  '/give': typeof GiveRoute
  '/how-to-delete-data': typeof HowToDeleteDataRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/fr/data-deletion': typeof FrDataDeletionRoute
  '/fr/eula': typeof FrEulaRoute
  '/fr/eula-en': typeof FrEulaEnRoute
  '/fr/give': typeof FrGiveRoute
  '/fr/how-to-delete-data': typeof FrHowToDeleteDataRoute
  '/fr/politique-de-confidentialite': typeof FrPolitiqueDeConfidentialiteRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/studies/$id': typeof StudiesIdRoute
  '/fr/': typeof FrIndexRoute
  '/fr/studies/$id': typeof FrStudiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/eula': typeof EulaRoute
  '/eula-en': typeof EulaEnRoute
  '/give': typeof GiveRoute
  '/how-to-delete-data': typeof HowToDeleteDataRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/fr/data-deletion': typeof FrDataDeletionRoute
  '/fr/eula': typeof FrEulaRoute
  '/fr/eula-en': typeof FrEulaEnRoute
  '/fr/give': typeof FrGiveRoute
  '/fr/how-to-delete-data': typeof FrHowToDeleteDataRoute
  '/fr/politique-de-confidentialite': typeof FrPolitiqueDeConfidentialiteRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/studies/$id': typeof StudiesIdRoute
  '/fr': typeof FrIndexRoute
  '/fr/studies/$id': typeof FrStudiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/eula': typeof EulaRoute
  '/eula-en': typeof EulaEnRoute
  '/give': typeof GiveRoute
  '/how-to-delete-data': typeof HowToDeleteDataRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/fr/data-deletion': typeof FrDataDeletionRoute
  '/fr/eula': typeof FrEulaRoute
  '/fr/eula-en': typeof FrEulaEnRoute
  '/fr/give': typeof FrGiveRoute
  '/fr/how-to-delete-data': typeof FrHowToDeleteDataRoute
  '/fr/politique-de-confidentialite': typeof FrPolitiqueDeConfidentialiteRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/studies/$id': typeof StudiesIdRoute
  '/fr/': typeof FrIndexRoute
  '/fr/studies/$id': typeof FrStudiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-deletion'
    | '/eula'
    | '/eula-en'
    | '/give'
    | '/how-to-delete-data'
    | '/politique-de-confidentialite'
    | '/privacy-policy'
    | '/fr/data-deletion'
    | '/fr/eula'
    | '/fr/eula-en'
    | '/fr/give'
    | '/fr/how-to-delete-data'
    | '/fr/politique-de-confidentialite'
    | '/fr/privacy-policy'
    | '/studies/$id'
    | '/fr/'
    | '/fr/studies/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-deletion'
    | '/eula'
    | '/eula-en'
    | '/give'
    | '/how-to-delete-data'
    | '/politique-de-confidentialite'
    | '/privacy-policy'
    | '/fr/data-deletion'
    | '/fr/eula'
    | '/fr/eula-en'
    | '/fr/give'
    | '/fr/how-to-delete-data'
    | '/fr/politique-de-confidentialite'
    | '/fr/privacy-policy'
    | '/studies/$id'
    | '/fr'
    | '/fr/studies/$id'
  id:
    | '__root__'
    | '/'
    | '/data-deletion'
    | '/eula'
    | '/eula-en'
    | '/give'
    | '/how-to-delete-data'
    | '/politique-de-confidentialite'
    | '/privacy-policy'
    | '/fr/data-deletion'
    | '/fr/eula'
    | '/fr/eula-en'
    | '/fr/give'
    | '/fr/how-to-delete-data'
    | '/fr/politique-de-confidentialite'
    | '/fr/privacy-policy'
    | '/studies/$id'
    | '/fr/'
    | '/fr/studies/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataDeletionRoute: typeof DataDeletionRoute
  EulaRoute: typeof EulaRoute
  EulaEnRoute: typeof EulaEnRoute
  GiveRoute: typeof GiveRoute
  HowToDeleteDataRoute: typeof HowToDeleteDataRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  FrDataDeletionRoute: typeof FrDataDeletionRoute
  FrEulaRoute: typeof FrEulaRoute
  FrEulaEnRoute: typeof FrEulaEnRoute
  FrGiveRoute: typeof FrGiveRoute
  FrHowToDeleteDataRoute: typeof FrHowToDeleteDataRoute
  FrPolitiqueDeConfidentialiteRoute: typeof FrPolitiqueDeConfidentialiteRoute
  FrPrivacyPolicyRoute: typeof FrPrivacyPolicyRoute
  StudiesIdRoute: typeof StudiesIdRoute
  FrIndexRoute: typeof FrIndexRoute
  FrStudiesIdRoute: typeof FrStudiesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eula': {
      id: '/eula'
      path: '/eula'
      fullPath: '/eula'
      preLoaderRoute: typeof EulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eula-en': {
      id: '/eula-en'
      path: '/eula-en'
      fullPath: '/eula-en'
      preLoaderRoute: typeof EulaEnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-delete-data': {
      id: '/how-to-delete-data'
      path: '/how-to-delete-data'
      fullPath: '/how-to-delete-data'
      preLoaderRoute: typeof HowToDeleteDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/data-deletion': {
      id: '/fr/data-deletion'
      path: '/fr/data-deletion'
      fullPath: '/fr/data-deletion'
      preLoaderRoute: typeof FrDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/eula': {
      id: '/fr/eula'
      path: '/fr/eula'
      fullPath: '/fr/eula'
      preLoaderRoute: typeof FrEulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/eula-en': {
      id: '/fr/eula-en'
      path: '/fr/eula-en'
      fullPath: '/fr/eula-en'
      preLoaderRoute: typeof FrEulaEnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/give': {
      id: '/fr/give'
      path: '/fr/give'
      fullPath: '/fr/give'
      preLoaderRoute: typeof FrGiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/how-to-delete-data': {
      id: '/fr/how-to-delete-data'
      path: '/fr/how-to-delete-data'
      fullPath: '/fr/how-to-delete-data'
      preLoaderRoute: typeof FrHowToDeleteDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/politique-de-confidentialite': {
      id: '/fr/politique-de-confidentialite'
      path: '/fr/politique-de-confidentialite'
      fullPath: '/fr/politique-de-confidentialite'
      preLoaderRoute: typeof FrPolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/privacy-policy': {
      id: '/fr/privacy-policy'
      path: '/fr/privacy-policy'
      fullPath: '/fr/privacy-policy'
      preLoaderRoute: typeof FrPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies/$id': {
      id: '/studies/$id'
      path: '/studies/$id'
      fullPath: '/studies/$id'
      preLoaderRoute: typeof StudiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/studies/$id': {
      id: '/fr/studies/$id'
      path: '/fr/studies/$id'
      fullPath: '/fr/studies/$id'
      preLoaderRoute: typeof FrStudiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataDeletionRoute: DataDeletionRoute,
  EulaRoute: EulaRoute,
  EulaEnRoute: EulaEnRoute,
  GiveRoute: GiveRoute,
  HowToDeleteDataRoute: HowToDeleteDataRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  FrDataDeletionRoute: FrDataDeletionRoute,
  FrEulaRoute: FrEulaRoute,
  FrEulaEnRoute: FrEulaEnRoute,
  FrGiveRoute: FrGiveRoute,
  FrHowToDeleteDataRoute: FrHowToDeleteDataRoute,
  FrPolitiqueDeConfidentialiteRoute: FrPolitiqueDeConfidentialiteRoute,
  FrPrivacyPolicyRoute: FrPrivacyPolicyRoute,
  StudiesIdRoute: StudiesIdRoute,
  FrIndexRoute: FrIndexRoute,
  FrStudiesIdRoute: FrStudiesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
