/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as EulaRouteImport } from './routes/eula'
import { Route as EulaEnRouteImport } from './routes/eula-en'
import { Route as GiveRouteImport } from './routes/give'
import { Route as HowToDeleteDataRouteImport } from './routes/how-to-delete-data'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BibleIndexRouteImport } from './routes/bible.index'
import { Route as BibleSplatRouteImport } from './routes/bible.$'
import { Route as BibleVersionRouteImport } from './routes/bible.$version'
import { Route as CommentaryLanguageRouteImport } from './routes/commentary.$language'
import { Route as DictionaryLanguageRouteImport } from './routes/dictionary.$language'
import { Route as FrIndexRouteImport } from './routes/fr.index'
import { Route as FrBibleRouteImport } from './routes/fr.bible'
import { Route as FrDataDeletionRouteImport } from './routes/fr.data-deletion'
import { Route as FrEulaRouteImport } from './routes/fr.eula'
import { Route as FrEulaEnRouteImport } from './routes/fr.eula-en'
import { Route as FrGiveRouteImport } from './routes/fr.give'
import { Route as FrHowToDeleteDataRouteImport } from './routes/fr.how-to-delete-data'
import { Route as FrPolitiqueDeConfidentialiteRouteImport } from './routes/fr.politique-de-confidentialite'
import { Route as FrPrivacyPolicyRouteImport } from './routes/fr.privacy-policy'
import { Route as NaveLanguageRouteImport } from './routes/nave.$language'
import { Route as SitemapsNameRouteImport } from './routes/sitemaps.$name'
import { Route as StrongCodeRouteImport } from './routes/strong.$code'
import { Route as StudiesIdRouteImport } from './routes/studies.$id'
import { Route as TimelineLanguageRouteImport } from './routes/timeline.$language'
import { Route as CommentaryLanguageResourceRouteImport } from './routes/commentary.$language_.$resource'
import { Route as DictionaryLanguageWorkRouteImport } from './routes/dictionary.$language_.$work'
import { Route as FrStudiesIdRouteImport } from './routes/fr.studies.$id'
import { Route as NaveLanguageTopicRouteImport } from './routes/nave.$language_.$topic'
import { Route as StrongLanguageCodeRouteImport } from './routes/strong.$language.$code'
import { Route as TimelineLanguageSlugRouteImport } from './routes/timeline.$language_.$slug'
import { Route as DictionaryLanguageWorkLetterRouteImport } from './routes/dictionary.$language_.$work_.$letter'
import { Route as NaveLanguageIndexLetterRouteImport } from './routes/nave.$language_.index.$letter'
import { Route as StrongLanguageCodeConcordanceRouteImport } from './routes/strong.$language.$code_.concordance'
import { Route as StrongLanguageLexiconLetterRouteImport } from './routes/strong.$language.$lexicon.$letter'
import { Route as CommentaryLanguageResourceBookChapterRouteImport } from './routes/commentary.$language_.$resource_.$book.$chapter'
import { Route as DictionaryLanguageWorkEntryIdSlugRouteImport } from './routes/dictionary.$language_.$work_.$entryId.$slug'
import { Route as NaveLanguageIndexLetterPageRouteImport } from './routes/nave.$language_.index.$letter_.$page'
import { Route as StrongLanguageCodeConcordancePageRouteImport } from './routes/strong.$language.$code_.concordance_.$page'
import { Route as CommentaryLanguageResourceBookChapterSectionRouteImport } from './routes/commentary.$language_.$resource_.$book.$chapter_.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const EulaRoute = EulaRouteImport.update({
  id: '/eula',
  path: '/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const EulaEnRoute = EulaEnRouteImport.update({
  id: '/eula-en',
  path: '/eula-en',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToDeleteDataRoute = HowToDeleteDataRouteImport.update({
  id: '/how-to-delete-data',
  path: '/how-to-delete-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleSplatRoute = BibleSplatRouteImport.update({
  id: '/bible/$',
  path: '/bible/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleVersionRoute = BibleVersionRouteImport.update({
  id: '/bible/$version',
  path: '/bible/$version',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentaryLanguageRoute = CommentaryLanguageRouteImport.update({
  id: '/commentary/$language',
  path: '/commentary/$language',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryLanguageRoute = DictionaryLanguageRouteImport.update({
  id: '/dictionary/$language',
  path: '/dictionary/$language',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBibleRoute = FrBibleRouteImport.update({
  id: '/fr/bible',
  path: '/fr/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const FrDataDeletionRoute = FrDataDeletionRouteImport.update({
  id: '/fr/data-deletion',
  path: '/fr/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const FrEulaRoute = FrEulaRouteImport.update({
  id: '/fr/eula',
  path: '/fr/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const FrEulaEnRoute = FrEulaEnRouteImport.update({
  id: '/fr/eula-en',
  path: '/fr/eula-en',
  getParentRoute: () => rootRouteImport,
} as any)
const FrGiveRoute = FrGiveRouteImport.update({
  id: '/fr/give',
  path: '/fr/give',
  getParentRoute: () => rootRouteImport,
} as any)
const FrHowToDeleteDataRoute = FrHowToDeleteDataRouteImport.update({
  id: '/fr/how-to-delete-data',
  path: '/fr/how-to-delete-data',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPolitiqueDeConfidentialiteRoute =
  FrPolitiqueDeConfidentialiteRouteImport.update({
    id: '/fr/politique-de-confidentialite',
    path: '/fr/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const FrPrivacyPolicyRoute = FrPrivacyPolicyRouteImport.update({
  id: '/fr/privacy-policy',
  path: '/fr/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NaveLanguageRoute = NaveLanguageRouteImport.update({
  id: '/nave/$language',
  path: '/nave/$language',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsNameRoute = SitemapsNameRouteImport.update({
  id: '/sitemaps/$name',
  path: '/sitemaps/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const StrongCodeRoute = StrongCodeRouteImport.update({
  id: '/strong/$code',
  path: '/strong/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesIdRoute = StudiesIdRouteImport.update({
  id: '/studies/$id',
  path: '/studies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineLanguageRoute = TimelineLanguageRouteImport.update({
  id: '/timeline/$language',
  path: '/timeline/$language',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentaryLanguageResourceRoute =
  CommentaryLanguageResourceRouteImport.update({
    id: '/commentary/$language_/$resource',
    path: '/commentary/$language/$resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DictionaryLanguageWorkRoute = DictionaryLanguageWorkRouteImport.update({
  id: '/dictionary/$language_/$work',
  path: '/dictionary/$language/$work',
  getParentRoute: () => rootRouteImport,
} as any)
const FrStudiesIdRoute = FrStudiesIdRouteImport.update({
  id: '/fr/studies/$id',
  path: '/fr/studies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NaveLanguageTopicRoute = NaveLanguageTopicRouteImport.update({
  id: '/nave/$language_/$topic',
  path: '/nave/$language/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const StrongLanguageCodeRoute = StrongLanguageCodeRouteImport.update({
  id: '/strong/$language/$code',
  path: '/strong/$language/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineLanguageSlugRoute = TimelineLanguageSlugRouteImport.update({
  id: '/timeline/$language_/$slug',
  path: '/timeline/$language/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryLanguageWorkLetterRoute =
  DictionaryLanguageWorkLetterRouteImport.update({
    id: '/dictionary/$language_/$work_/$letter',
    path: '/dictionary/$language/$work/$letter',
    getParentRoute: () => rootRouteImport,
  } as any)
const NaveLanguageIndexLetterRoute = NaveLanguageIndexLetterRouteImport.update({
  id: '/nave/$language_/index/$letter',
  path: '/nave/$language/index/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const StrongLanguageCodeConcordanceRoute =
  StrongLanguageCodeConcordanceRouteImport.update({
    id: '/strong/$language/$code_/concordance',
    path: '/strong/$language/$code/concordance',
    getParentRoute: () => rootRouteImport,
  } as any)
const StrongLanguageLexiconLetterRoute =
  StrongLanguageLexiconLetterRouteImport.update({
    id: '/strong/$language/$lexicon/$letter',
    path: '/strong/$language/$lexicon/$letter',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommentaryLanguageResourceBookChapterRoute =
  CommentaryLanguageResourceBookChapterRouteImport.update({
    id: '/commentary/$language_/$resource_/$book/$chapter',
    path: '/commentary/$language/$resource/$book/$chapter',
    getParentRoute: () => rootRouteImport,
  } as any)
const DictionaryLanguageWorkEntryIdSlugRoute =
  DictionaryLanguageWorkEntryIdSlugRouteImport.update({
    id: '/dictionary/$language_/$work_/$entryId/$slug',
    path: '/dictionary/$language/$work/$entryId/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const NaveLanguageIndexLetterPageRoute =
  NaveLanguageIndexLetterPageRouteImport.update({
    id: '/nave/$language_/index/$letter_/$page',
    path: '/nave/$language/index/$letter/$page',
    getParentRoute: () => rootRouteImport,
  } as any)
const StrongLanguageCodeConcordancePageRoute =
  StrongLanguageCodeConcordancePageRouteImport.update({
    id: '/strong/$language/$code_/concordance_/$page',
    path: '/strong/$language/$code/concordance/$page',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommentaryLanguageResourceBookChapterSectionRoute =
  CommentaryLanguageResourceBookChapterSectionRouteImport.update({
    id: '/commentary/$language_/$resource_/$book/$chapter_/$section',
    path: '/commentary/$language/$resource/$book/$chapter/$section',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/eula': typeof EulaRoute
  '/eula-en': typeof EulaEnRoute
  '/give': typeof GiveRoute
  '/how-to-delete-data': typeof HowToDeleteDataRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bible/$': typeof BibleSplatRoute
  '/bible/$version': typeof BibleVersionRoute
  '/commentary/$language': typeof CommentaryLanguageRoute
  '/dictionary/$language': typeof DictionaryLanguageRoute
  '/fr/bible': typeof FrBibleRoute
  '/fr/data-deletion': typeof FrDataDeletionRoute
  '/fr/eula': typeof FrEulaRoute
  '/fr/eula-en': typeof FrEulaEnRoute
  '/fr/give': typeof FrGiveRoute
  '/fr/how-to-delete-data': typeof FrHowToDeleteDataRoute
  '/fr/politique-de-confidentialite': typeof FrPolitiqueDeConfidentialiteRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/nave/$language': typeof NaveLanguageRoute
  '/sitemaps/$name': typeof SitemapsNameRoute
  '/strong/$code': typeof StrongCodeRoute
  '/studies/$id': typeof StudiesIdRoute
  '/timeline/$language': typeof TimelineLanguageRoute
  '/bible/': typeof BibleIndexRoute
  '/fr/': typeof FrIndexRoute
  '/commentary/$language/$resource': typeof CommentaryLanguageResourceRoute
  '/dictionary/$language/$work': typeof DictionaryLanguageWorkRoute
  '/fr/studies/$id': typeof FrStudiesIdRoute
  '/nave/$language/$topic': typeof NaveLanguageTopicRoute
  '/strong/$language/$code': typeof StrongLanguageCodeRoute
  '/timeline/$language/$slug': typeof TimelineLanguageSlugRoute
  '/dictionary/$language/$work/$letter': typeof DictionaryLanguageWorkLetterRoute
  '/strong/$language/$code/concordance': typeof StrongLanguageCodeConcordanceRoute
  '/strong/$language/$lexicon/$letter': typeof StrongLanguageLexiconLetterRoute
  '/nave/$language/index/$letter': typeof NaveLanguageIndexLetterRoute
  '/commentary/$language/$resource/$book/$chapter': typeof CommentaryLanguageResourceBookChapterRoute
  '/dictionary/$language/$work/$entryId/$slug': typeof DictionaryLanguageWorkEntryIdSlugRoute
  '/strong/$language/$code/concordance/$page': typeof StrongLanguageCodeConcordancePageRoute
  '/nave/$language/index/$letter/$page': typeof NaveLanguageIndexLetterPageRoute
  '/commentary/$language/$resource/$book/$chapter/$section': typeof CommentaryLanguageResourceBookChapterSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/eula': typeof EulaRoute
  '/eula-en': typeof EulaEnRoute
  '/give': typeof GiveRoute
  '/how-to-delete-data': typeof HowToDeleteDataRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bible/$': typeof BibleSplatRoute
  '/bible/$version': typeof BibleVersionRoute
  '/commentary/$language': typeof CommentaryLanguageRoute
  '/dictionary/$language': typeof DictionaryLanguageRoute
  '/fr/bible': typeof FrBibleRoute
  '/fr/data-deletion': typeof FrDataDeletionRoute
  '/fr/eula': typeof FrEulaRoute
  '/fr/eula-en': typeof FrEulaEnRoute
  '/fr/give': typeof FrGiveRoute
  '/fr/how-to-delete-data': typeof FrHowToDeleteDataRoute
  '/fr/politique-de-confidentialite': typeof FrPolitiqueDeConfidentialiteRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/nave/$language': typeof NaveLanguageRoute
  '/sitemaps/$name': typeof SitemapsNameRoute
  '/strong/$code': typeof StrongCodeRoute
  '/studies/$id': typeof StudiesIdRoute
  '/timeline/$language': typeof TimelineLanguageRoute
  '/bible': typeof BibleIndexRoute
  '/fr': typeof FrIndexRoute
  '/commentary/$language/$resource': typeof CommentaryLanguageResourceRoute
  '/dictionary/$language/$work': typeof DictionaryLanguageWorkRoute
  '/fr/studies/$id': typeof FrStudiesIdRoute
  '/nave/$language/$topic': typeof NaveLanguageTopicRoute
  '/strong/$language/$code': typeof StrongLanguageCodeRoute
  '/timeline/$language/$slug': typeof TimelineLanguageSlugRoute
  '/dictionary/$language/$work/$letter': typeof DictionaryLanguageWorkLetterRoute
  '/strong/$language/$code/concordance': typeof StrongLanguageCodeConcordanceRoute
  '/strong/$language/$lexicon/$letter': typeof StrongLanguageLexiconLetterRoute
  '/nave/$language/index/$letter': typeof NaveLanguageIndexLetterRoute
  '/commentary/$language/$resource/$book/$chapter': typeof CommentaryLanguageResourceBookChapterRoute
  '/dictionary/$language/$work/$entryId/$slug': typeof DictionaryLanguageWorkEntryIdSlugRoute
  '/strong/$language/$code/concordance/$page': typeof StrongLanguageCodeConcordancePageRoute
  '/nave/$language/index/$letter/$page': typeof NaveLanguageIndexLetterPageRoute
  '/commentary/$language/$resource/$book/$chapter/$section': typeof CommentaryLanguageResourceBookChapterSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/eula': typeof EulaRoute
  '/eula-en': typeof EulaEnRoute
  '/give': typeof GiveRoute
  '/how-to-delete-data': typeof HowToDeleteDataRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bible/$': typeof BibleSplatRoute
  '/bible/$version': typeof BibleVersionRoute
  '/commentary/$language': typeof CommentaryLanguageRoute
  '/dictionary/$language': typeof DictionaryLanguageRoute
  '/fr/bible': typeof FrBibleRoute
  '/fr/data-deletion': typeof FrDataDeletionRoute
  '/fr/eula': typeof FrEulaRoute
  '/fr/eula-en': typeof FrEulaEnRoute
  '/fr/give': typeof FrGiveRoute
  '/fr/how-to-delete-data': typeof FrHowToDeleteDataRoute
  '/fr/politique-de-confidentialite': typeof FrPolitiqueDeConfidentialiteRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/nave/$language': typeof NaveLanguageRoute
  '/sitemaps/$name': typeof SitemapsNameRoute
  '/strong/$code': typeof StrongCodeRoute
  '/studies/$id': typeof StudiesIdRoute
  '/timeline/$language': typeof TimelineLanguageRoute
  '/bible/': typeof BibleIndexRoute
  '/fr/': typeof FrIndexRoute
  '/commentary/$language_/$resource': typeof CommentaryLanguageResourceRoute
  '/dictionary/$language_/$work': typeof DictionaryLanguageWorkRoute
  '/fr/studies/$id': typeof FrStudiesIdRoute
  '/nave/$language_/$topic': typeof NaveLanguageTopicRoute
  '/strong/$language/$code': typeof StrongLanguageCodeRoute
  '/timeline/$language_/$slug': typeof TimelineLanguageSlugRoute
  '/dictionary/$language_/$work_/$letter': typeof DictionaryLanguageWorkLetterRoute
  '/strong/$language/$code_/concordance': typeof StrongLanguageCodeConcordanceRoute
  '/strong/$language/$lexicon/$letter': typeof StrongLanguageLexiconLetterRoute
  '/nave/$language_/index/$letter': typeof NaveLanguageIndexLetterRoute
  '/commentary/$language_/$resource_/$book/$chapter': typeof CommentaryLanguageResourceBookChapterRoute
  '/dictionary/$language_/$work_/$entryId/$slug': typeof DictionaryLanguageWorkEntryIdSlugRoute
  '/strong/$language/$code_/concordance_/$page': typeof StrongLanguageCodeConcordancePageRoute
  '/nave/$language_/index/$letter_/$page': typeof NaveLanguageIndexLetterPageRoute
  '/commentary/$language_/$resource_/$book/$chapter_/$section': typeof CommentaryLanguageResourceBookChapterSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-deletion'
    | '/eula'
    | '/eula-en'
    | '/give'
    | '/how-to-delete-data'
    | '/politique-de-confidentialite'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/bible/$'
    | '/bible/$version'
    | '/commentary/$language'
    | '/dictionary/$language'
    | '/fr/bible'
    | '/fr/data-deletion'
    | '/fr/eula'
    | '/fr/eula-en'
    | '/fr/give'
    | '/fr/how-to-delete-data'
    | '/fr/politique-de-confidentialite'
    | '/fr/privacy-policy'
    | '/nave/$language'
    | '/sitemaps/$name'
    | '/strong/$code'
    | '/studies/$id'
    | '/timeline/$language'
    | '/bible/'
    | '/fr/'
    | '/commentary/$language/$resource'
    | '/dictionary/$language/$work'
    | '/fr/studies/$id'
    | '/nave/$language/$topic'
    | '/strong/$language/$code'
    | '/timeline/$language/$slug'
    | '/dictionary/$language/$work/$letter'
    | '/strong/$language/$code/concordance'
    | '/strong/$language/$lexicon/$letter'
    | '/nave/$language/index/$letter'
    | '/commentary/$language/$resource/$book/$chapter'
    | '/dictionary/$language/$work/$entryId/$slug'
    | '/strong/$language/$code/concordance/$page'
    | '/nave/$language/index/$letter/$page'
    | '/commentary/$language/$resource/$book/$chapter/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-deletion'
    | '/eula'
    | '/eula-en'
    | '/give'
    | '/how-to-delete-data'
    | '/politique-de-confidentialite'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/bible/$'
    | '/bible/$version'
    | '/commentary/$language'
    | '/dictionary/$language'
    | '/fr/bible'
    | '/fr/data-deletion'
    | '/fr/eula'
    | '/fr/eula-en'
    | '/fr/give'
    | '/fr/how-to-delete-data'
    | '/fr/politique-de-confidentialite'
    | '/fr/privacy-policy'
    | '/nave/$language'
    | '/sitemaps/$name'
    | '/strong/$code'
    | '/studies/$id'
    | '/timeline/$language'
    | '/bible'
    | '/fr'
    | '/commentary/$language/$resource'
    | '/dictionary/$language/$work'
    | '/fr/studies/$id'
    | '/nave/$language/$topic'
    | '/strong/$language/$code'
    | '/timeline/$language/$slug'
    | '/dictionary/$language/$work/$letter'
    | '/strong/$language/$code/concordance'
    | '/strong/$language/$lexicon/$letter'
    | '/nave/$language/index/$letter'
    | '/commentary/$language/$resource/$book/$chapter'
    | '/dictionary/$language/$work/$entryId/$slug'
    | '/strong/$language/$code/concordance/$page'
    | '/nave/$language/index/$letter/$page'
    | '/commentary/$language/$resource/$book/$chapter/$section'
  id:
    | '__root__'
    | '/'
    | '/data-deletion'
    | '/eula'
    | '/eula-en'
    | '/give'
    | '/how-to-delete-data'
    | '/politique-de-confidentialite'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/bible/$'
    | '/bible/$version'
    | '/commentary/$language'
    | '/dictionary/$language'
    | '/fr/bible'
    | '/fr/data-deletion'
    | '/fr/eula'
    | '/fr/eula-en'
    | '/fr/give'
    | '/fr/how-to-delete-data'
    | '/fr/politique-de-confidentialite'
    | '/fr/privacy-policy'
    | '/nave/$language'
    | '/sitemaps/$name'
    | '/strong/$code'
    | '/studies/$id'
    | '/timeline/$language'
    | '/bible/'
    | '/fr/'
    | '/commentary/$language_/$resource'
    | '/dictionary/$language_/$work'
    | '/fr/studies/$id'
    | '/nave/$language_/$topic'
    | '/strong/$language/$code'
    | '/timeline/$language_/$slug'
    | '/dictionary/$language_/$work_/$letter'
    | '/strong/$language/$code_/concordance'
    | '/strong/$language/$lexicon/$letter'
    | '/nave/$language_/index/$letter'
    | '/commentary/$language_/$resource_/$book/$chapter'
    | '/dictionary/$language_/$work_/$entryId/$slug'
    | '/strong/$language/$code_/concordance_/$page'
    | '/nave/$language_/index/$letter_/$page'
    | '/commentary/$language_/$resource_/$book/$chapter_/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataDeletionRoute: typeof DataDeletionRoute
  EulaRoute: typeof EulaRoute
  EulaEnRoute: typeof EulaEnRoute
  GiveRoute: typeof GiveRoute
  HowToDeleteDataRoute: typeof HowToDeleteDataRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BibleSplatRoute: typeof BibleSplatRoute
  BibleVersionRoute: typeof BibleVersionRoute
  CommentaryLanguageRoute: typeof CommentaryLanguageRoute
  DictionaryLanguageRoute: typeof DictionaryLanguageRoute
  FrBibleRoute: typeof FrBibleRoute
  FrDataDeletionRoute: typeof FrDataDeletionRoute
  FrEulaRoute: typeof FrEulaRoute
  FrEulaEnRoute: typeof FrEulaEnRoute
  FrGiveRoute: typeof FrGiveRoute
  FrHowToDeleteDataRoute: typeof FrHowToDeleteDataRoute
  FrPolitiqueDeConfidentialiteRoute: typeof FrPolitiqueDeConfidentialiteRoute
  FrPrivacyPolicyRoute: typeof FrPrivacyPolicyRoute
  NaveLanguageRoute: typeof NaveLanguageRoute
  SitemapsNameRoute: typeof SitemapsNameRoute
  StrongCodeRoute: typeof StrongCodeRoute
  StudiesIdRoute: typeof StudiesIdRoute
  TimelineLanguageRoute: typeof TimelineLanguageRoute
  BibleIndexRoute: typeof BibleIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  CommentaryLanguageResourceRoute: typeof CommentaryLanguageResourceRoute
  DictionaryLanguageWorkRoute: typeof DictionaryLanguageWorkRoute
  FrStudiesIdRoute: typeof FrStudiesIdRoute
  NaveLanguageTopicRoute: typeof NaveLanguageTopicRoute
  StrongLanguageCodeRoute: typeof StrongLanguageCodeRoute
  TimelineLanguageSlugRoute: typeof TimelineLanguageSlugRoute
  DictionaryLanguageWorkLetterRoute: typeof DictionaryLanguageWorkLetterRoute
  StrongLanguageCodeConcordanceRoute: typeof StrongLanguageCodeConcordanceRoute
  StrongLanguageLexiconLetterRoute: typeof StrongLanguageLexiconLetterRoute
  NaveLanguageIndexLetterRoute: typeof NaveLanguageIndexLetterRoute
  CommentaryLanguageResourceBookChapterRoute: typeof CommentaryLanguageResourceBookChapterRoute
  DictionaryLanguageWorkEntryIdSlugRoute: typeof DictionaryLanguageWorkEntryIdSlugRoute
  StrongLanguageCodeConcordancePageRoute: typeof StrongLanguageCodeConcordancePageRoute
  NaveLanguageIndexLetterPageRoute: typeof NaveLanguageIndexLetterPageRoute
  CommentaryLanguageResourceBookChapterSectionRoute: typeof CommentaryLanguageResourceBookChapterSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eula': {
      id: '/eula'
      path: '/eula'
      fullPath: '/eula'
      preLoaderRoute: typeof EulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eula-en': {
      id: '/eula-en'
      path: '/eula-en'
      fullPath: '/eula-en'
      preLoaderRoute: typeof EulaEnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-delete-data': {
      id: '/how-to-delete-data'
      path: '/how-to-delete-data'
      fullPath: '/how-to-delete-data'
      preLoaderRoute: typeof HowToDeleteDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/bible'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$': {
      id: '/bible/$'
      path: '/bible/$'
      fullPath: '/bible/$'
      preLoaderRoute: typeof BibleSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$version': {
      id: '/bible/$version'
      path: '/bible/$version'
      fullPath: '/bible/$version'
      preLoaderRoute: typeof BibleVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commentary/$language': {
      id: '/commentary/$language'
      path: '/commentary/$language'
      fullPath: '/commentary/$language'
      preLoaderRoute: typeof CommentaryLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary/$language': {
      id: '/dictionary/$language'
      path: '/dictionary/$language'
      fullPath: '/dictionary/$language'
      preLoaderRoute: typeof DictionaryLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/bible': {
      id: '/fr/bible'
      path: '/fr/bible'
      fullPath: '/fr/bible'
      preLoaderRoute: typeof FrBibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/data-deletion': {
      id: '/fr/data-deletion'
      path: '/fr/data-deletion'
      fullPath: '/fr/data-deletion'
      preLoaderRoute: typeof FrDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/eula': {
      id: '/fr/eula'
      path: '/fr/eula'
      fullPath: '/fr/eula'
      preLoaderRoute: typeof FrEulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/eula-en': {
      id: '/fr/eula-en'
      path: '/fr/eula-en'
      fullPath: '/fr/eula-en'
      preLoaderRoute: typeof FrEulaEnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/give': {
      id: '/fr/give'
      path: '/fr/give'
      fullPath: '/fr/give'
      preLoaderRoute: typeof FrGiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/how-to-delete-data': {
      id: '/fr/how-to-delete-data'
      path: '/fr/how-to-delete-data'
      fullPath: '/fr/how-to-delete-data'
      preLoaderRoute: typeof FrHowToDeleteDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/politique-de-confidentialite': {
      id: '/fr/politique-de-confidentialite'
      path: '/fr/politique-de-confidentialite'
      fullPath: '/fr/politique-de-confidentialite'
      preLoaderRoute: typeof FrPolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/privacy-policy': {
      id: '/fr/privacy-policy'
      path: '/fr/privacy-policy'
      fullPath: '/fr/privacy-policy'
      preLoaderRoute: typeof FrPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nave/$language': {
      id: '/nave/$language'
      path: '/nave/$language'
      fullPath: '/nave/$language'
      preLoaderRoute: typeof NaveLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/$name': {
      id: '/sitemaps/$name'
      path: '/sitemaps/$name'
      fullPath: '/sitemaps/$name'
      preLoaderRoute: typeof SitemapsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strong/$code': {
      id: '/strong/$code'
      path: '/strong/$code'
      fullPath: '/strong/$code'
      preLoaderRoute: typeof StrongCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies/$id': {
      id: '/studies/$id'
      path: '/studies/$id'
      fullPath: '/studies/$id'
      preLoaderRoute: typeof StudiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$language': {
      id: '/timeline/$language'
      path: '/timeline/$language'
      fullPath: '/timeline/$language'
      preLoaderRoute: typeof TimelineLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commentary/$language_/$resource': {
      id: '/commentary/$language_/$resource'
      path: '/commentary/$language/$resource'
      fullPath: '/commentary/$language/$resource'
      preLoaderRoute: typeof CommentaryLanguageResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary/$language_/$work': {
      id: '/dictionary/$language_/$work'
      path: '/dictionary/$language/$work'
      fullPath: '/dictionary/$language/$work'
      preLoaderRoute: typeof DictionaryLanguageWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/studies/$id': {
      id: '/fr/studies/$id'
      path: '/fr/studies/$id'
      fullPath: '/fr/studies/$id'
      preLoaderRoute: typeof FrStudiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nave/$language_/$topic': {
      id: '/nave/$language_/$topic'
      path: '/nave/$language/$topic'
      fullPath: '/nave/$language/$topic'
      preLoaderRoute: typeof NaveLanguageTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strong/$language/$code': {
      id: '/strong/$language/$code'
      path: '/strong/$language/$code'
      fullPath: '/strong/$language/$code'
      preLoaderRoute: typeof StrongLanguageCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$language_/$slug': {
      id: '/timeline/$language_/$slug'
      path: '/timeline/$language/$slug'
      fullPath: '/timeline/$language/$slug'
      preLoaderRoute: typeof TimelineLanguageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary/$language_/$work_/$letter': {
      id: '/dictionary/$language_/$work_/$letter'
      path: '/dictionary/$language/$work/$letter'
      fullPath: '/dictionary/$language/$work/$letter'
      preLoaderRoute: typeof DictionaryLanguageWorkLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nave/$language_/index/$letter': {
      id: '/nave/$language_/index/$letter'
      path: '/nave/$language/index/$letter'
      fullPath: '/nave/$language/index/$letter'
      preLoaderRoute: typeof NaveLanguageIndexLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strong/$language/$code_/concordance': {
      id: '/strong/$language/$code_/concordance'
      path: '/strong/$language/$code/concordance'
      fullPath: '/strong/$language/$code/concordance'
      preLoaderRoute: typeof StrongLanguageCodeConcordanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strong/$language/$lexicon/$letter': {
      id: '/strong/$language/$lexicon/$letter'
      path: '/strong/$language/$lexicon/$letter'
      fullPath: '/strong/$language/$lexicon/$letter'
      preLoaderRoute: typeof StrongLanguageLexiconLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commentary/$language_/$resource_/$book/$chapter': {
      id: '/commentary/$language_/$resource_/$book/$chapter'
      path: '/commentary/$language/$resource/$book/$chapter'
      fullPath: '/commentary/$language/$resource/$book/$chapter'
      preLoaderRoute: typeof CommentaryLanguageResourceBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary/$language_/$work_/$entryId/$slug': {
      id: '/dictionary/$language_/$work_/$entryId/$slug'
      path: '/dictionary/$language/$work/$entryId/$slug'
      fullPath: '/dictionary/$language/$work/$entryId/$slug'
      preLoaderRoute: typeof DictionaryLanguageWorkEntryIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nave/$language_/index/$letter_/$page': {
      id: '/nave/$language_/index/$letter_/$page'
      path: '/nave/$language/index/$letter/$page'
      fullPath: '/nave/$language/index/$letter/$page'
      preLoaderRoute: typeof NaveLanguageIndexLetterPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strong/$language/$code_/concordance_/$page': {
      id: '/strong/$language/$code_/concordance_/$page'
      path: '/strong/$language/$code/concordance/$page'
      fullPath: '/strong/$language/$code/concordance/$page'
      preLoaderRoute: typeof StrongLanguageCodeConcordancePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commentary/$language_/$resource_/$book/$chapter_/$section': {
      id: '/commentary/$language_/$resource_/$book/$chapter_/$section'
      path: '/commentary/$language/$resource/$book/$chapter/$section'
      fullPath: '/commentary/$language/$resource/$book/$chapter/$section'
      preLoaderRoute: typeof CommentaryLanguageResourceBookChapterSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataDeletionRoute: DataDeletionRoute,
  EulaRoute: EulaRoute,
  EulaEnRoute: EulaEnRoute,
  GiveRoute: GiveRoute,
  HowToDeleteDataRoute: HowToDeleteDataRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BibleSplatRoute: BibleSplatRoute,
  BibleVersionRoute: BibleVersionRoute,
  CommentaryLanguageRoute: CommentaryLanguageRoute,
  DictionaryLanguageRoute: DictionaryLanguageRoute,
  FrBibleRoute: FrBibleRoute,
  FrDataDeletionRoute: FrDataDeletionRoute,
  FrEulaRoute: FrEulaRoute,
  FrEulaEnRoute: FrEulaEnRoute,
  FrGiveRoute: FrGiveRoute,
  FrHowToDeleteDataRoute: FrHowToDeleteDataRoute,
  FrPolitiqueDeConfidentialiteRoute: FrPolitiqueDeConfidentialiteRoute,
  FrPrivacyPolicyRoute: FrPrivacyPolicyRoute,
  NaveLanguageRoute: NaveLanguageRoute,
  SitemapsNameRoute: SitemapsNameRoute,
  StrongCodeRoute: StrongCodeRoute,
  StudiesIdRoute: StudiesIdRoute,
  TimelineLanguageRoute: TimelineLanguageRoute,
  BibleIndexRoute: BibleIndexRoute,
  FrIndexRoute: FrIndexRoute,
  CommentaryLanguageResourceRoute: CommentaryLanguageResourceRoute,
  DictionaryLanguageWorkRoute: DictionaryLanguageWorkRoute,
  FrStudiesIdRoute: FrStudiesIdRoute,
  NaveLanguageTopicRoute: NaveLanguageTopicRoute,
  StrongLanguageCodeRoute: StrongLanguageCodeRoute,
  TimelineLanguageSlugRoute: TimelineLanguageSlugRoute,
  DictionaryLanguageWorkLetterRoute: DictionaryLanguageWorkLetterRoute,
  StrongLanguageCodeConcordanceRoute: StrongLanguageCodeConcordanceRoute,
  StrongLanguageLexiconLetterRoute: StrongLanguageLexiconLetterRoute,
  NaveLanguageIndexLetterRoute: NaveLanguageIndexLetterRoute,
  CommentaryLanguageResourceBookChapterRoute:
    CommentaryLanguageResourceBookChapterRoute,
  DictionaryLanguageWorkEntryIdSlugRoute:
    DictionaryLanguageWorkEntryIdSlugRoute,
  StrongLanguageCodeConcordancePageRoute:
    StrongLanguageCodeConcordancePageRoute,
  NaveLanguageIndexLetterPageRoute: NaveLanguageIndexLetterPageRoute,
  CommentaryLanguageResourceBookChapterSectionRoute:
    CommentaryLanguageResourceBookChapterSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
