import { COMMENTARY_DESCRIPTIONS } from './commentaryDescriptions'

export type CommentaryLanguage = 'fr' | 'en'

export type CommentaryCatalogEntry = {
  id: string
  publicationId: string
  shortName: string
  title: string
  description: Partial<Record<CommentaryLanguage, string>>
  author: string
  languages: readonly CommentaryLanguage[]
  tradition: string
  tags: readonly string[]
  rights: string
}

type CommentaryCatalogInput = Omit<CommentaryCatalogEntry, 'description' | 'publicationId'> & {
  publicationId?: string
}

const commentary = (entry: CommentaryCatalogInput): CommentaryCatalogEntry => ({
  ...entry,
  publicationId: entry.publicationId ?? entry.id,
  description: COMMENTARY_DESCRIPTIONS[entry.id as keyof typeof COMMENTARY_DESCRIPTIONS],
})

export const COMMENTARY_CATALOG = [
  commentary({
    id: 'acbc',
    shortName: 'Clarke',
    title: 'Adam Clarke Bible Commentary',
    author: 'Adam Clarke',
    languages: ['en', 'fr'],
    tradition: 'Protestantisme',
    tags: ['Méthodiste', 'Wesleyen', 'Arminien'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'barnes',
    shortName: 'Barnes',
    title: 'Barnes’ Notes on the Bible',
    author: 'Albert Barnes',
    languages: ['en', 'fr'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Presbytérien'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'mhy-fr',
    publicationId: 'MHY',
    shortName: 'Henry',
    title: 'Commentaire concis de Matthew Henry',
    author: 'Matthew Henry',
    languages: ['fr'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Presbytérien', 'Puritain'],
    rights: '© Éditions CLÉ / Dominique Osché · tous droits réservés',
  }),
  commentary({
    id: 'mhcc',
    shortName: 'Henry',
    title: 'Matthew Henry Concise Commentary',
    author: 'Matthew Henry',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Presbytérien', 'Puritain'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'aquifer-fr',
    shortName: 'Aquifer',
    title: 'Tyndale Open Study Notes',
    author: 'Tyndale House Publishers',
    languages: ['en', 'fr'],
    tradition: 'Protestantisme',
    tags: ['Évangélique'],
    rights: '© Mission Mutual / Tyndale House Publishers · CC BY-SA 4.0',
  }),
  commentary({
    id: 'jfb',
    shortName: 'JFB',
    title: 'Jamieson–Fausset–Brown Commentary',
    author: 'R. Jamieson, A. R. Fausset, D. Brown',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Presbytérien', 'Anglican'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'fre-aug',
    shortName: 'Augustin',
    title: 'Commentaires de saint Augustin',
    author: 'Augustin d’Hippone',
    languages: ['fr'],
    tradition: 'Christianisme ancien',
    tags: ['Patristique', 'Patristique occidentale'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'fre-chry',
    shortName: 'Chrysostome',
    title: 'Commentaires de saint Jean Chrysostome',
    author: 'Jean Chrysostome',
    languages: ['fr'],
    tradition: 'Christianisme ancien',
    tags: ['Patristique', 'Patristique orientale'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'rashi-en',
    shortName: 'Rachi',
    title: 'Rashi on Tanakh',
    author: 'Rachi',
    languages: ['en'],
    tradition: 'Judaïsme',
    tags: ['Rabbinique'],
    rights: 'Metsudah Publications / Judaica Press · CC BY',
  }),
  commentary({
    id: 'calvin',
    shortName: 'Calvin',
    title: 'Calvin’s Commentaries',
    author: 'Jean Calvin',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Calviniste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'kd',
    shortName: 'K&D',
    title: 'Keil & Delitzsch Commentary',
    author: 'C. F. Keil et F. Delitzsch',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Luthérien'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'wesley',
    shortName: 'Wesley',
    title: 'John Wesley’s Notes',
    author: 'John Wesley',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Méthodiste', 'Wesleyen', 'Arminien'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'treasury-david',
    shortName: 'Treasury',
    title: 'The Treasury of David',
    author: 'Charles Spurgeon',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Baptiste', 'Réformé', 'Évangélique'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'catena-aurea',
    shortName: 'Catena',
    title: 'Catena Aurea',
    author: 'Thomas d’Aquin (compilateur)',
    languages: ['en'],
    tradition: 'Catholicisme',
    tags: ['Patristique', 'Scolastique', 'Thomiste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'abbott',
    shortName: 'Abbott',
    title: 'Illustrated New Testament',
    author: 'John S. C. Abbott et Jacob Abbott',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Congrégationaliste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'burkitt',
    shortName: 'Burkitt',
    title: 'Burkitt’s Expository Notes',
    author: 'William Burkitt',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Anglican'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'darby-notes',
    shortName: 'Darby',
    title: 'Darby Translation Notes',
    author: 'John Nelson Darby',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Évangélique', 'Frères', 'Dispensationaliste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'family-notes',
    shortName: 'Family',
    title: 'Family Bible Notes',
    author: 'Justin Edwards et collaborateurs',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Évangélique', 'Congrégationaliste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'geneva-notes',
    shortName: 'Genève',
    title: 'Geneva Bible Translation Notes',
    author: 'Traducteurs de la Bible de Genève',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Calviniste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'king-comments',
    shortName: 'KingComments',
    title: 'Kingcomments',
    author: 'Ger de Koning',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Évangélique', 'Frères', 'Dispensationaliste'],
    rights: '© Ger de Koning · tous droits réservés',
  }),
  commentary({
    id: 'lightfoot',
    shortName: 'Lightfoot',
    title: 'John Lightfoot Commentary',
    author: 'John Lightfoot',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Puritain', 'Réformé'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'luther',
    shortName: 'Luther',
    title: 'Luther’s Commentary on Selected Bible Passages',
    author: 'Martin Luther',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Luthérien'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'mhc',
    shortName: 'Henry complet',
    title: 'Matthew Henry’s Complete Commentary',
    author: 'Matthew Henry',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Presbytérien', 'Puritain'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'mhm',
    shortName: 'Henry moderne',
    title: 'Matthew Henry’s Modern English Commentary',
    author: 'Matthew Henry ; adaptation STEPBible',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Presbytérien', 'Puritain'],
    rights: 'STEPBible · CC BY 4.0',
  }),
  commentary({
    id: 'pnt',
    shortName: 'PNT',
    title: 'The People’s New Testament',
    author: 'B. W. Johnson',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Restaurationniste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'rwp',
    shortName: 'RWP',
    title: 'Robertson’s Word Pictures',
    author: 'A. T. Robertson',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Baptiste', 'Évangélique'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'scofield',
    shortName: 'Scofield',
    title: 'Scofield Reference Notes, 1917 Edition',
    author: 'C. I. Scofield',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Évangélique', 'Dispensationaliste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'fourfold-gospel',
    shortName: 'Fourfold',
    title: 'The Fourfold Gospel and Commentary on Acts',
    author: 'J. W. McGarvey et Philip Y. Pendleton',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Restaurationniste'],
    rights: 'Domaine public',
  }),
  commentary({
    id: 'douay-rheims-notes',
    shortName: 'Douay',
    title: 'Original Douay–Rheims Annotations',
    author: 'Collège anglais de Douai–Reims',
    languages: ['en'],
    tradition: 'Catholicisme',
    tags: ['Catholique'],
    rights: 'CC0 1.0',
  }),
  commentary({
    id: 'bible-annotee',
    shortName: 'Bible annotée',
    title: 'Bible Annotée de Neuchâtel',
    author: 'Collectif Bonnet, Bovet, Godet et collaborateurs',
    languages: ['fr'],
    tradition: 'Protestantisme',
    tags: ['Réformé', 'Réformé francophone'],
    rights: 'ThéoTeX · tous droits réservés',
  }),
  commentary({
    id: 'sdabc',
    shortName: 'SDA Commentary',
    title: 'Seventh-day Adventist Bible Commentary',
    author: 'Francis D. Nichol (dir.) et contributeurs',
    languages: ['en', 'fr'],
    tradition: 'Protestantisme',
    tags: ['Adventiste'],
    rights: 'Review and Herald Publishing Association · tous droits réservés',
  }),
  commentary({
    id: 'egw-writings',
    shortName: 'EGW Writings',
    title: 'EGW Writings',
    author: 'Ellen G. White',
    languages: ['en'],
    tradition: 'Protestantisme',
    tags: ['Adventiste'],
    rights: 'Ellen G. White Estate · tous droits réservés',
  }),
] as const satisfies readonly CommentaryCatalogEntry[]

export const COMMENTARY_CATALOG_BY_ID = new Map(COMMENTARY_CATALOG.map(entry => [entry.id, entry]))

export const getCommentaryCatalogForLanguage = (language: CommentaryLanguage) =>
  COMMENTARY_CATALOG.filter(entry => entry.languages.includes(language))

export const getCommentaryByPublicationId = (publicationId: string, language: CommentaryLanguage) =>
  COMMENTARY_CATALOG.find(
    entry => entry.publicationId === publicationId && entry.languages.includes(language)
  )
