export const NAVIGATE_TO_PERICOPE = 'NAVIGATE_TO_PERICOPE'
export const NAVIGATE_TO_BIBLE_VIEW = 'NAVIGATE_TO_BIBLE_VIEW'
export const NAVIGATE_TO_BIBLICAL_ENTITY = 'NAVIGATE_TO_BIBLICAL_ENTITY'
export const NAVIGATE_TO_STRONG = 'NAVIGATE_TO_STRONG'
export const DOWNLOAD_CHAPTER_ENTITIES = 'DOWNLOAD_CHAPTER_ENTITIES'
export const DISMISS_CONTEXTUAL_INFORMATION = 'DISMISS_CONTEXTUAL_INFORMATION'
export const NAVIGATE_TO_BIBLE_NOTE = 'NAVIGATE_TO_BIBLE_NOTE'
export const NAVIGATE_TO_BIBLE_LINK = 'NAVIGATE_TO_BIBLE_LINK'
export const NAVIGATE_TO_RELATION_ENDPOINT = 'NAVIGATE_TO_RELATION_ENDPOINT'
export const SHOW_TOAST = 'SHOW_TOAST'
export const NAVIGATE_TO_BIBLE_VERSE_DETAIL = 'NAVIGATE_TO_BIBLE_VERSE_DETAIL'
export const NAVIGATE_TO_VERSE_LINKS = 'NAVIGATE_TO_VERSE_LINKS'
export const NAVIGATE_TO_VERSE_STUDY_RELATIONS = 'NAVIGATE_TO_VERSE_STUDY_RELATIONS'
export const OPEN_STRONG_SELECTION = 'OPEN_STRONG_SELECTION'
export const TOGGLE_SELECTED_VERSE = 'TOGGLE_SELECTED_VERSE'
export const NAVIGATE_TO_VERSION = 'NAVIGATE_TO_VERSION'
export const REMOVE_PARALLEL_VERSION = 'REMOVE_PARALLEL_VERSION'
export const ADD_PARALLEL_VERSION = 'ADD_PARALLEL_VERSION'
export const SWIPE_LEFT = 'SWIPE_LEFT'
export const SWIPE_RIGHT = 'SWIPE_RIGHT'
export const SWIPE_UP = 'SWIPE_UP'
export const SWIPE_DOWN = 'SWIPE_DOWN'
export const OPEN_HIGHLIGHT_TAGS = 'OPEN_HIGHLIGHT_TAGS'
export const OPEN_BOOKMARK_MODAL = 'OPEN_BOOKMARK_MODAL'
export const NAVIGATE_TO_TAG = 'NAVIGATE_TO_TAG'
export const EXPAND_CONTEXT = 'EXPAND_CONTEXT'
export const COLLAPSE_CONTEXT = 'COLLAPSE_CONTEXT'
export const CLEAR_FOCUS_VERSES = 'CLEAR_FOCUS_VERSES'
export const SET_BIBLE_OVERLAY_OPEN = 'SET_BIBLE_OVERLAY_OPEN'

// Annotation mode actions
export const ENTER_ANNOTATION_MODE = 'ENTER_ANNOTATION_MODE'
export const SELECTION_CHANGED = 'SELECTION_CHANGED'
export const CREATE_ANNOTATION = 'CREATE_ANNOTATION'
export const ERASE_SELECTION = 'ERASE_SELECTION'
export const CLEAR_SELECTION = 'CLEAR_SELECTION'
export const ANNOTATION_SELECTED = 'ANNOTATION_SELECTED'
export const SET_SCROLL_ENABLED = 'SET_SCROLL_ENABLED'

// Cross-version annotation indicator actions
export const OPEN_CROSS_VERSION_MODAL = 'OPEN_CROSS_VERSION_MODAL'

// Verse tags modal
export const OPEN_VERSE_TAGS_MODAL = 'OPEN_VERSE_TAGS_MODAL'
export const OPEN_CANONICAL_BIBLE_NOTE = 'OPEN_CANONICAL_BIBLE_NOTE'
export const OPEN_CANONICAL_BIBLE_REFERENCE = 'OPEN_CANONICAL_BIBLE_REFERENCE'

// Error/download actions
export const DOWNLOAD_BIBLE_VERSION = 'DOWNLOAD_BIBLE_VERSION'
export const OPEN_DOWNLOADS = 'OPEN_DOWNLOADS'
export const RESET_BIBLE_DATABASE = 'RESET_BIBLE_DATABASE'
export const RETRY_BIBLE_RESOURCE = 'RETRY_BIBLE_RESOURCE'

const PERSONAL_BIBLE_DATA_ACTIONS = new Set<string>([
  NAVIGATE_TO_BIBLE_NOTE,
  NAVIGATE_TO_BIBLE_LINK,
  NAVIGATE_TO_RELATION_ENDPOINT,
  NAVIGATE_TO_VERSE_LINKS,
  NAVIGATE_TO_VERSE_STUDY_RELATIONS,
  TOGGLE_SELECTED_VERSE,
  OPEN_HIGHLIGHT_TAGS,
  OPEN_BOOKMARK_MODAL,
  NAVIGATE_TO_TAG,
  ENTER_ANNOTATION_MODE,
  SELECTION_CHANGED,
  CREATE_ANNOTATION,
  ERASE_SELECTION,
  ANNOTATION_SELECTED,
  OPEN_CROSS_VERSION_MODAL,
  OPEN_VERSE_TAGS_MODAL,
])

export const isPersonalBibleDataAction = (actionType: string): boolean =>
  PERSONAL_BIBLE_DATA_ACTIONS.has(actionType)
