const crypto = require('crypto')
const fs = require('fs')
const path = require('path')

const { withDangerousMod } = require('expo/config-plugins')

// `<version>:<base64 32-byte key>` pairs separated by commas (ADR-0065).
const ARCHIVE_KEYS_ENV = 'BIBLE_STRONG_ARCHIVE_KEYS'
const MODULE_DIRECTORY = path.join('modules', 'bible-strong-archive')
const SWIFT_OUTPUT = path.join(MODULE_DIRECTORY, 'ios', 'Generated', 'ArchiveKeyMaterial.swift')
const KOTLIN_OUTPUT = path.join(
  MODULE_DIRECTORY,
  'android/src/main/java/expo/modules/biblestrongarchive/generated/ArchiveKeyMaterial.kt'
)
const HEADER =
  'Generated by plugins/withBibleStrongArchiveKeys.js. Contains key material: never commit.'

const parseArchiveKeys = value => {
  if (!value || !value.trim()) return []
  const versions = new Set()
  return value.split(',').map(pair => {
    const separator = pair.indexOf(':')
    const version = Number(pair.slice(0, separator).trim())
    const key = Buffer.from(pair.slice(separator + 1).trim(), 'base64')
    if (separator <= 0 || !Number.isSafeInteger(version) || version <= 0) {
      throw new Error(`${ARCHIVE_KEYS_ENV} entries must look like <positive version>:<base64 key>`)
    }
    if (key.length !== 32)
      throw new Error(`${ARCHIVE_KEYS_ENV} key ${version} must decode to 32 bytes`)
    if (versions.has(version)) throw new Error(`${ARCHIVE_KEYS_ENV} repeats key version ${version}`)
    versions.add(version)
    return { version, key }
  })
}

// Masking only keeps the key out of string searches of the binary; it is not encryption.
const maskKeys = (keys, randomBytes = crypto.randomBytes) =>
  keys.map(({ version, key }) => {
    const mask = randomBytes(key.length)
    return { version, masked: [...key].map((byte, index) => byte ^ mask[index]), mask: [...mask] }
  })

const renderSwift = entries => `// ${HEADER}
enum ArchiveKeyMaterial {
  static let entries: [ArchiveKeyMaterialEntry] = [
${entries
  .map(
    ({ version, masked, mask }) =>
      `    ArchiveKeyMaterialEntry(version: ${version}, masked: [${masked.join(', ')}], mask: [${mask.join(', ')}]),`
  )
  .join('\n')}
  ]
}
`

const renderKotlin = entries => `// ${HEADER}
package expo.modules.biblestrongarchive.generated

import expo.modules.biblestrongarchive.ArchiveKeyMaterialEntry

internal object ArchiveKeyMaterial {
  val entries: List<ArchiveKeyMaterialEntry> =
    listOf(
${entries
  .map(
    ({ version, masked, mask }) =>
      `      ArchiveKeyMaterialEntry(${version}, intArrayOf(${masked.join(', ')}), intArrayOf(${mask.join(', ')})),`
  )
  .join('\n')}
    )
}
`

const writeGenerated = async (projectRoot, relativePath, contents) => {
  const outputPath = path.join(projectRoot, relativePath)
  await fs.promises.mkdir(path.dirname(outputPath), { recursive: true })
  await fs.promises.writeFile(outputPath, contents)
}

// Without keys the files still exist, so the module compiles and reports keys as unavailable.
const withBibleStrongArchiveKeys = config => {
  const keys = parseArchiveKeys(process.env[ARCHIVE_KEYS_ENV])
  config = withDangerousMod(config, [
    'ios',
    async config => {
      await writeGenerated(config.modRequest.projectRoot, SWIFT_OUTPUT, renderSwift(maskKeys(keys)))
      return config
    },
  ])
  return withDangerousMod(config, [
    'android',
    async config => {
      await writeGenerated(
        config.modRequest.projectRoot,
        KOTLIN_OUTPUT,
        renderKotlin(maskKeys(keys))
      )
      return config
    },
  ])
}

module.exports = withBibleStrongArchiveKeys
module.exports.parseArchiveKeys = parseArchiveKeys
module.exports.maskKeys = maskKeys
module.exports.renderSwift = renderSwift
module.exports.renderKotlin = renderKotlin
